    FALSE                       = 0
    TRUE                        = 1

    SYSVAR_CLOCK                = 0x80
    SYSVAR_FRAMES               = 0x81

    COLOR_NONE                  = 0x0
    COLOR_BLACK                 = 0x1
    COLOR_WHITE                 = 0x2
    COLOR_RED                   = 0x3
    COLOR_GREEN                 = 0x4
    COLOR_BLUE                  = 0x5

    ENTITY_PROP_ID              = 0x0
    ENTITY_PROP_TYPE            = 0x1
    ENTITY_PROP_STATE           = 0x2
    ENTITY_PROP_HIDDEN          = 0x3
    ENTITY_PROP_MVT_FRAME       = 0x4

    ENTITY_STATE_NORMAL         = 0x0

    TRANSFORM_X_ONLY            = 0x1
    TRANSFORM_Y_ONLY            = 0x2
    TRANSFORM_Z_ONLY            = 0x4
    TRANSFORM_THETA_ONLY        = 0x8
    TRANSFORM_XYZ_THETA         = 0xF
    TRANSFORM_ALL               = 0x1F

    TEXT_NONE                           = 0

    BGM_NONE            = 0

    PARTICLE_NONE               = 0
    PARTICLE_RED                = 1
    PARTICLE_GREEN              = 2
    PARTICLE_BLUE               = 3
    PARTICLE_RGB                = 4

    DYNAMIC_OBJ_NONE            = 0
